---
title: "Lab 06 - Functions and iterations"
author: "Alex Lee"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth = depth_pct,
    x = length_mm,
    y = width_mm,
    z = depth_mm,
    table = table_pct
  )
```


## Exercise 1

```{r}
# Do some preliminary investigations & cleaning

df1 <- diamonds %>% select(price, carat, clarity, cut)

ggplot(data = df1, mapping = aes(x = carat, y = price, color = clarity)) +
  geom_point(alpha = 0.3) + theme_bw() +
  xlab("Carat") +
  ylab("Price, USD") +
  guides(color = guide_legend(title = "Diamond Clarity"))

ggplot(data = df1, mapping = aes(x = cut, fill = clarity)) +
  geom_bar(alpha = 0.5) + theme_bw() +
  xlab("Cut of Diamond") +
  ylab("Number of Round Cut Diamonds") +
  guides(color = guide_legend(title = "Price, USD"))

ggplot(data = df1, mapping = aes( x = price)) +
  geom_histogram(fill = "#ADD8E6") + 
  theme_bw() +
  xlab("Price of Diamond, USD") +
  ylab("Number of Round Cut Diamonds") 


```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

# Overall table_mm arithmetic mean?






# table_mm arithmetic mean within each clarity category






```

_Add your comment here_

## Exercise 3

_Do derivation on paper, unless you know how to write LaTeX code_


## Exercise 4

```{r}
# Write gmean() command



```

## Exercise 5

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples


```


## Exercise 6

```{r}
# Copy gmean() from Ex4 and edit it to check the input





# Copy your code from Ex 5 to test your new command





```


## Exercise 7

```{r}
# Overall table_mm geometic mean?






# table_mm geometic mean within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```
